name: RIS
version: '${project.version}'
main: org.bali.ris.Main
api-version: '1.20'
load: POSTWORLD
commands:
  ris:
    description: Main command for the RIS plugin
    usage: /ris <subcommand> [args]