
# How mutch time will be spent after pick up to respawn the item
respawntime: 240

# Locations, and details
ItemInfos:
  item1:
    world: 'world'
    x: 100.0
    y: 64.0
    z: 100.0
    item: DIAMOND
    value: 10
    command: "eco give %player% %value%"
  item2:
    world: 'world'
    x: 200.0
    y: 64.0
    z: 200.0
    item: EMERALD
    value: 20
    command: "eco give %player% %value%"